# inputs to create an image ----------------------------------------------------------------------------------
measurement_set: "path/to/data.ms"
source_name: "target"
image_size: 512

# if just want to image one band, toggle True and specify band. The "split" param below still applies.
# for an SED, don't have to change the single-freq params: just make sure use_single_band = FALSE
use_single_band: True
single_band: "EVLA_X"

# splits are "whole" for one image per band with all spws, "halves" for two images split down spws, or "both" 
split: "both"

# point source inputs ----------------------------------------------------------------------------------------
try_point_source: True
fitting_procedure: "basic"
# if True, prints results as a dictionary in terminal
print_results: True
# if True, writes results as an excel sheet in imfit_files subdirectory
write_results: False

# optional imfit params for "advanced" fitting procedure ------------------------------------------------------
# Specify casa region file or string to use in calculating the near-source RMS. If None, default annulus used.
source_free_region: None 
# if True, writes casa region files for beam, source region of fit, fit result, and source-free region
write_regions: False
# if True, bypasses the error that will be thrown if the source-free region has a suspected source
override_sfr_request: True
